spring:
  application:
    name: url-shortening

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Garoupa97
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379
    timeout: 6000

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: Garoupa97
    driver-class-name: org.postgresql.Driver
    locations: /home/daniel-silva/Documentos/ideaProjects/url-shortening/src/main/resources/db/migration
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history

server:
  port: 8099